"""add email verification

Revision ID: 12956edee61d
Revises: d70ce09760ef
Create Date: 2026-08-08 23:21:14.353222

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12956edee61d"
down_revision: str | Sequence[str] | None = "d70ce09760ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column("users", sa.Column("otp_hash", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("otp_expires_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_expires_at")
    op.drop_column("users", "otp_hash")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
