"""create is_pinned , is_favoriate , is_archieved Column

Revision ID: d70ce09760ef
Revises: 14f0cfb3e126
Create Date: 2026-08-05 08:32:32.595502

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d70ce09760ef"
down_revision: str | Sequence[str] | None = "14f0cfb3e126"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "notes",
        sa.Column(
            "is_pinned",
            sa.Boolean(),
            nullable=False,
            server_default=text("false"),
        ),
    )

    op.add_column(
        "notes",
        sa.Column(
            "is_favorite",
            sa.Boolean(),
            nullable=False,
            server_default=text("false"),
        ),
    )

    op.add_column(
        "notes",
        sa.Column(
            "is_archived",
            sa.Boolean(),
            nullable=False,
            server_default=text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "is_archived")
    op.drop_column("notes", "is_favorite")
    op.drop_column("notes", "is_pinned")
    # ### end Alembic commands ###
